### ISSUE TITLE
Peer Preview:  Added / Last Modified is not displayed in the details section 

### ISSUE THREAD

**Issue by Camelia-Orcid** [ORCID/orcid-angular#1052]
The Details section of Peer Review doesn't have the Added/ Last Modified information. The pre-speedup listing includes [those.](url)

**Comment by DanielPalafox** [comment]
it was requested to remove those dates https://trello.com/c/uCUD5t2B/7513-remove-added-and-last-modified-dates-from-peer-review-activities
