### ISSUE TITLE
Peer Review: Delete review  confirmation dialog different in speedup vs. current

### ISSUE THREAD

**Issue by Camelia-Orcid** [ORCID/orcid-angular#1056]
speedup
<img width="919" alt="Screenshot 2021-09-06 at 13 34 21" src="https://user-images.githubusercontent.com/62257307/132218576-f6c27ad8-8e3a-4bad-a979-17c81444a19a.png">

current version
<img width="550" alt="Screenshot 2021-09-06 at 13 38 50" src="https://user-images.githubusercontent.com/62257307/132218840-322d8955-da1a-4853-a5af-de3aa9e03bd4.png">

**Comment by DanielPalafox** [comment]
I created a card to develop this missing feature https://trello.com/c/NTTDNtyc/7540-speedup-q3-verification-email-banner-and-modal
