### ISSUE TITLE
Works: Duplicated 'Add manually' option on the 'Add' dropdown menu

### ISSUE THREAD

**Issue by dandineen** [ORCID/orcid-angular#1087]
There are two ‘Add manually’ options - one at the top and one at the bottom of the dropdown.

![Screenshot 2021-09-10 at 14 13 33](https://user-images.githubusercontent.com/869732/132858640-1e5fe7f8-fc4f-4dd1-867a-c519d7b1354d.png)

**NOTE:** I think this issue has already been fixed as I'm not seeing it happening in the latest release of the private page on QA.

However the 'Add manually' link is now at the top of the list whereas it should be at the bottom!

**Comment by DanielPalafox** [comment]
This has already been fixed in the previous release.
