### ISSUE TITLE
Unavailable route for Oauth authorization page 

### ISSUE THREAD

**Issue by leomendoza123** [ORCID/orcid-angular#262]
## Description 

The `/oauth/authorize` route can't be overwritten by NGINX  to load the authorization page since this is what is currently used to load the request information to the java section. 

### Expected behavior

A user who navigates to the `/oauth/authorize` page I want to see the authorization page on the new app, and the request section is created on the backend. 

### Steps to replicate 

1- create an Nginx rule on `register-vagrant` to redirected  `/oauth/authorize*`  into the Angular app 
2- try to authorize an app calling an authorize URL like 
```
https://dev.orcid.org/oauth/authorize?client_id=APP-U1P5ZAG2ZGMD6PTF&response_type=code&scope=/authenticate%20openid&redirect_uri=https://developers.google.com/oauthplayground	
```
the backend will never add the request info to the section

**Comment by leomendoza123** [comment]
This is the current workflow of the Oauth 

![image](https://user-images.githubusercontent.com/2119626/83825153-b8dc3a80-a695-11ea-9f46-728eba375573.png)

It is producing this issue and issue #260 

If we add an endpoint on Orcid Source that receives the Oauth arguments, populates the `request` on the section and return this request data, we can potentially move into the following workflow 

![image](https://user-images.githubusercontent.com/2119626/83825422-88e16700-a696-11ea-9664-f7d8a395fee4.png)

**Comment by amontenegro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OAuth authorization (8)](https://trello.com/c/nQeUeqcD/280-oauth-authorization-8)

**Comment by leomendoza123** [comment]
@DanielPalafox  I have created the following function that mocks the call for this expected new endpoint. Please have a look: 

https://github.com/ORCID/orcid-angular/blob/0081de502e77b1167fefca0599d4e9b0acf32236/src/app/core/oauth/oauth.service.ts#L116-L144

Please make any change if needed

**Comment by leomendoza123** [comment]
Solved https://github.com/ORCID/orcid-angular/pull/315/files
