### ISSUE TITLE
NAME - Name fields need to be clearer

### ISSUE THREAD

**Issue by DanielPalafox** [ORCID/orcid-angular#848]
https://docs.google.com/document/d/1r5qu-zahp3Uyg-QMV-FjDobeJWtVzDlQdf8zXlba9Y0/edit#heading=h.fb8qd0i53m7s

**Comment by dandineen** [comment]
I've put together examples of the expected layout and behaviour with the various 'name' combinations. This _should_ cover everything you need to know but give me a shout if you think anything is still missing.

https://www.figma.com/file/7HKUvrf3H8cin0aGvM230J/My-ORCID-https-trello.com-c-RJt4waZS?node-id=1840%3A136
