### ISSUE TITLE
'Manage' and 'Preview' stripes don't cover *all* possible combinations

### ISSUE THREAD

**Issue by dandineen** [ORCID/orcid-angular#863]
https://docs.google.com/document/d/1r5qu-zahp3Uyg-QMV-FjDobeJWtVzDlQdf8zXlba9Y0/edit#bookmark=id.ih1t2vos3lwe

The page is showing a 'Previewing public page' stripe but this shouldn't be shown unless the user is signed in.

Note: _This is another issue where the designs didn't cover every variation needed._

We have introduced a 'stripe' that sits underneath the main header and helps the user to know _at a glance_ what version of a record they are looking at. The original designs didn't cover all eventualities so I've updated the designs to cover them:

- Signed in and managing your own record
- Signed in and previewing the public version of your own record
- Signed in and managing another users record as a trusted individual
- Signed in and previewing the public version of another users record as a trusted individual

![My ORCID - Manage and preview stripes](https://user-images.githubusercontent.com/869732/119469379-341f7c00-bd3f-11eb-8b14-aac2573d680c.jpg)

https://www.figma.com/file/7HKUvrf3H8cin0aGvM230J/My-ORCID-https-trello.com-c-RJt4waZS?node-id=1850%3A6

**Comment by DanielPalafox** [comment]
@leomendoza123 the text is inaccurate it says `You are previewing a public version your record` and it should be `You are previewing the public version of your record`
